### ISSUE TITLE
Few questions about the project

### ISSUE THREAD

**Issue by TrueAccelerator** [joeybab3/audio-reactive-led-strip#7]
1.    Can it be completed on Rpi4 successfully?

2.    If I power the tape through a separate power source and only connect ground and data to Rpi, do I risk any damage should I make a mistake of some sort?

3.    Why do Rpi, power source and led tape MUST share common ground exactly? Do I simply have to connect RPI ground pin to the cable that goes from the led tape to the ground on the controller?

**Comment by joeybab3** [comment]
This fork exists solely for me to create PR's for https://github.com/scottlawsonbc/audio-reactive-led-strip
